### ISSUE TITLE
Tiled JSON format

### ISSUE THREAD

**Issue by MarcusRiemer** [arcaneenergy/tilemap-level-editor#1]
I am posting this because I saw that your JSON format is not 100% finished. Are you aware of the [tiled JSON format](https://doc.mapeditor.org/en/stable/reference/json-map-format/)? Being compatible to that would really open up the space of compatible assets.

**Comment by arcaneenergy** [comment]
Thanks. I will take a look.

**Comment by arcaneenergy** [comment]
Most of the work is done. You can find the work in the tiled-json-format branch. There's a small problem. When importing the level into Tiled it says invalid data for layer 1. I'm not using Tiled so I don't know where the error could be. I'll leave it as is for now.
